version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4467:4467"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-200-72-77.compute-1.amazonaws.com
            database: dfv3aiibidr27t
            schema: public
            user: uckswcsgbgwmsx
            password: a56c8f5f167c71bfbea1fd4922b4763c6604f0252ae994a18336c042fedca466
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
